
from pydantic import BaseModel, Field


class OptimizeRequest(BaseModel):
    prompt: str = Field(
        ...,
        min_length=3,
        description="The raw, unoptimized prompt to improve.",
        examples=["How do I write a web server in FastAPI?"],
    )
    tone: str | None = Field(
        default="professional",
        description="The desired tone for the response generated by the optimized prompt.",
        examples=["professional", "conversational", "academic", "concise", "creative"],
    )
    detail_level: str | None = Field(
        default="balanced",
        description="The depth of detail expected in the response.",
        examples=["concise", "balanced", "detailed"],
    )
    target_audience: str | None = Field(
        default=None,
        description="Who the final response is intended for (e.g. developers, students, executives).",
        examples=["developers"],
    )
    groq_model: str | None = Field(
        default="llama3-8b-8192",
        description="The Groq LLM model used to perform the prompt optimization.",
        examples=["llama3-8b-8192", "llama3-70b-8192", "mixtral-8x7b-32768"],
    )


class OptimizeMetrics(BaseModel):
    tokens_before: int = Field(
        ..., description="Estimated token count of original prompt."
    )
    tokens_after: int = Field(
        ..., description="Estimated token count of optimized prompt."
    )
    processing_time_ms: float = Field(
        ..., description="FastAPI/Groq API server processing time in milliseconds."
    )


class OptimizeResponse(BaseModel):
    raw_prompt: str = Field(..., description="The original prompt input.")
    optimized_prompt: str = Field(
        ..., description="The fully optimized prompt, ready to use."
    )
    explanation: str = Field(
        ..., description="Markdown list explaining what changes were made and why."
    )
    metrics: OptimizeMetrics = Field(
        ..., description="Performance and token count metrics."
    )


class DetailResponse(BaseModel):
    detail: str = Field(..., description="A description of the error.")
