
from pydantic import BaseModel, Field, ConfigDict


class OptimizeRequest(BaseModel):
    prompt: str = Field(
        ...,
        min_length=3,
        description="The raw, unoptimized prompt to improve.",
        examples=["How do I write a web server in FastAPI?"],
    )
    tone: str | None = Field(
        default="professional",
        description="The desired tone for the response generated by the optimized prompt.",
        examples=["professional", "conversational", "academic", "concise", "creative"],
    )
    detail_level: str | None = Field(
        default="balanced",
        description="The depth of detail expected in the response.",
        examples=["concise", "balanced", "detailed"],
    )
    target_audience: str | None = Field(
        default=None,
        description="Who the final response is intended for (e.g. developers, students, executives).",
        examples=["developers"],
    )
    groq_model: str | None = Field(
        default="llama-3.1-8b-instant",
        description="The Groq LLM model used to perform the prompt optimization.",
        examples=["llama-3.1-8b-instant", "llama-3.3-70b-versatile", "mixtral-8x7b-32768"],
    )
    optimization_mode: str | None = Field(
        default="balanced",
        description="The optimization mode: save_tokens, balanced, max_quality.",
        examples=["save_tokens", "balanced", "max_quality"],
    )


class OptimizeMetrics(BaseModel):
    tokens_before: int = Field(
        ..., description="Estimated token count of original prompt."
    )
    tokens_after: int = Field(
        ..., description="Estimated token count of optimized prompt."
    )
    processing_time_ms: float = Field(
        ..., description="FastAPI/Groq API server processing time in milliseconds."
    )


class OptimizationResult(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    original_tokens: int = Field(..., alias="originalTokens")
    optimized_tokens: int = Field(..., alias="optimizedTokens")
    token_delta: int = Field(..., alias="tokenDelta")
    token_savings_percent: float = Field(..., alias="tokenSavingsPercent")
    optimization_accepted: bool = Field(..., alias="optimizationAccepted")
    optimization_mode: str = Field(..., alias="optimizationMode")
    status: str = Field(..., description="Accepted or Rejected status.")
    reason: str | None = Field(default=None, description="Reason for rejection, if applicable.")
    recommendation: str = Field(..., description="Recommendation (e.g. Use Original Prompt).")
    efficiency_score_original: float = Field(..., alias="efficiencyScoreOriginal")
    efficiency_score_optimized: float = Field(..., alias="efficiencyScoreOptimized")


class OptimizeResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    raw_prompt: str = Field(..., description="The original prompt input.")
    optimized_prompt: str = Field(
        ..., description="The fully optimized prompt, ready to use."
    )
    explanation: str = Field(
        ..., description="Markdown list explaining what changes were made and why."
    )
    metrics: OptimizeMetrics = Field(
        ..., description="Performance and token count metrics."
    )
    optimization_result: OptimizationResult = Field(
        ..., description="Detailed token optimization and validation result.", alias="optimizationResult"
    )


class DetailResponse(BaseModel):
    detail: str = Field(..., description="A description of the error.")
