/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize prompt
         * @description Analyze a raw prompt and return an improved version based on prompt engineering standards.
         */
        post: operations["optimize_api_v1_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DetailResponse */
        DetailResponse: {
            /**
             * Detail
             * @description A description of the error.
             */
            detail: string;
        };
        /** OptimizeMetrics */
        OptimizeMetrics: {
            /**
             * Tokens Before
             * @description Estimated token count of original prompt.
             */
            tokens_before: number;
            /**
             * Tokens After
             * @description Estimated token count of optimized prompt.
             */
            tokens_after: number;
            /**
             * Processing Time Ms
             * @description FastAPI/Groq API server processing time in milliseconds.
             */
            processing_time_ms: number;
        };
        /** OptimizeRequest */
        OptimizeRequest: {
            /**
             * Prompt
             * @description The raw, unoptimized prompt to improve.
             * @example How do I write a web server in FastAPI?
             */
            prompt: string;
            /**
             * Tone
             * @description The desired tone for the response generated by the optimized prompt.
             * @default professional
             * @example professional
             * @example conversational
             * @example academic
             * @example concise
             * @example creative
             */
            tone: string | null;
            /**
             * Detail Level
             * @description The depth of detail expected in the response.
             * @default balanced
             * @example concise
             * @example balanced
             * @example detailed
             */
            detail_level: string | null;
            /**
             * Target Audience
             * @description Who the final response is intended for (e.g. developers, students, executives).
             * @example developers
             */
            target_audience?: string | null;
            /**
             * Groq Model
             * @description The Groq LLM model used to perform the prompt optimization.
             * @default llama3-8b-8192
             * @example llama3-8b-8192
             * @example llama3-70b-8192
             * @example mixtral-8x7b-32768
             */
            groq_model: string | null;
        };
        /** OptimizeResponse */
        OptimizeResponse: {
            /**
             * Raw Prompt
             * @description The original prompt input.
             */
            raw_prompt: string;
            /**
             * Optimized Prompt
             * @description The fully optimized prompt, ready to use.
             */
            optimized_prompt: string;
            /**
             * Explanation
             * @description Markdown list explaining what changes were made and why.
             */
            explanation: string;
            /** @description Performance and token count metrics. */
            metrics: components["schemas"]["OptimizeMetrics"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    optimize_api_v1_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
}
